#file: noinspection Annotator
name: Publish Release By Tag
run-name: ${{ github.workflow }} ${{ inputs.releaseTag }} ${{ github.event.repository.updated_at}}
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: Release Tag
        required: true
        type: choice
        options:
          - v1.0.0
          - v0.0.8.1
          - v0.0.8
          - v0.0.7.2
          - v0.0.7.1
          - v0.0.7
          - v0.0.6
          - v0.0.5
          - v0.0.4
          - v0.0.3
          - v0.0.2
          - v0.0.1
permissions: { }
jobs:
  publish-release-by-tag:
    name: Publish Release By Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tag ${{ inputs.releaseTag }}
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ inputs.releaseTag }}
      - name: Get Commit Message
        run: |
          gitTopLevel="$(git rev-parse --show-toplevel)"
          versionCodeFilter="\(versionCode\s\+=\s\+\)\([[:digit:]]\+\)"
          versionCode=$(git show "$tag:mobile/build.gradle.kts" | grep -e "versionCode\s*=\s*" | sed -e "s/$versionCodeFilter/\2/" | xargs)

          cat "$gitTopLevel/fastlane/metadata/android/en/changelogs/$versionCode.txt"

          {
              echo 'COMMIT_MESSAGE<<EOF'
              cat "$gitTopLevel/fastlane/metadata/android/en/changelogs/$versionCode.txt"
              echo EOF
          } >> $GITHUB_ENV
      - name: Create local.properties
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > release_keystore.jks

          keystoreFile=$(realpath release_keystore.jks)

          echo "keystoreFile: $keystoreFile"

          echo "storeFile=$keystoreFile" >> local.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> local.properties
          echo "keyAlias=release_key" >> local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - name: Setup Python
        run: uv python install
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
      - name: Setup X Virtual Framebuffer
        run: sudo apt-get install -y libxext6 libxrender1 libxtst6 xvfb
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2.1.3
      - name: Build APK
        run: xvfb-run -a bash gradlew mobile:assembleRelease
      - name: Get APK Name
        run: |
          releaseApk=$(find mobile/build/outputs/apk/release/*.apk)
          echo $releaseApk
          echo ARTIFACT_NAME=$(basename $releaseApk) >> $GITHUB_ENV
          echo ARTIFACT_PATH=$releaseApk >> $GITHUB_ENV
      - name: Create Artifact ${{ env.ARTIFACT_NAME }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
          if-no-files-found: error
      - name: Publish Release ${{ github.ref_name }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.ARTIFACT_PATH }}
          tag: refs/tags/${{ inputs.releaseTag }}
          draft: false
          overwrite: true
          promote: true
          make_latest: true
          body: ${{ env.COMMIT_MESSAGE }}
          release_name: ${{ inputs.releaseTag }}
          repo_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
